FROM python:3.8
COPY . ./
RUN pip3 install -r requirements.txt

ENV data-folder '/'
ENV sent-emails-file 'sent_emails.csv'
ENV responded-emails-file 'responded.csv'
ENV customers-file 'userbase.csv'

CMD ["email_campaign_service.py"]
ENTRYPOINT ["python"]